# Sidebar navigation

- label: "Introduction"
  link: "/"
# - label: "Getting started"
#   link: "/getting-started"
- label: Projects
  items:
    - label: "React Movie App"
      link: "/projects/react-movie-app"
    - label: "Login Boiler Plage"
      link: "/projects/login-boiler-plate"
    - label: "React To Do App"
      link: "/projects/react-to-do-app"
    - label: "Vue Realestate App"
      link: "/projects/vue-realestate-app"
    - label: "WordPress Theme"
      link: "/projects/wordpress-theme"
    - label: "Northside Are Gallery"
      link: "/projects/northside-art-gallery"
- label: Notes
  items:
    - label: "React Basic"
      link: "/notes/react-basic"
    - label: "Node.js & Express basic"
      link: "/notes/nodejs-and-express-basic"
    - label: "ES6 Basic"
      link: "/notes/javascript-es6"
    - label: "Git & Github"
      link: "/notes/git-and-github"
    - label: "Gatsby.js deploy"
      link: "/notes/gatsby-deploy"
    - label: "Login Boiler Plate"
      link: "/notes/login-boiler-plate"
    - label: "CRUD MERN App"
      link: "/notes/crud-mern-app"
- label: Usage
  items:
    - label: "Creating docs"
      link: "/usage/creating-docs"
    - label: "Navigation"
      link: "/usage/navigation"
    - label: "Shadowing"
      link: "/usage/shadowing"
    - label: "Sidebar test"
      link: "/"
- label: More
  items:
    - label: "Github"
      link: https://github.com/rocketseat/gatsby-themes
